//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use crate::database::{new_db_pool, Db};

pub mod prelude;

pub mod cake;
pub mod cake_filling;
pub mod error;
pub mod filling;
pub mod fruit;

pub use self::error::{Error, Result};

#[derive(Clone)]
pub struct AppState {
    db: Db,
}

impl AppState {
    /// Constructor
    pub async fn new() -> Result<Self> {
        let db = new_db_pool().await?;

        Ok(AppState { db })
    }

    /// Returns the sqlx db pool reference.
    /// (Only for the model layer)
    pub(in crate::model) fn db(&self) -> &Db {
        &self.db
    }
}
