//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::cake::Entity as Cake;
pub use super::cake_filling::Entity as CakeFilling;
pub use super::filling::Entity as Filling;
pub use super::fruit::Entity as Fruit;
pub use super::user::Entity as User;
